baseURL: https://tonvanbart.github.io/europrez
title: "europrez"
defaultContentLanguage: en
languages:
    en:
        lang: en
        languageName: English
        weight: 1
MetaDataFormat: "yaml"
theme: "europrez"
menu:
    main:
    - name: Home
      pageRef: / 
      weight: 10
    - name: News
      pageRef: /News
      title: Latest news
      weight: 20
    - name: Past events
      pageRef: /Past
      weight: 30
    - name: EP30 PRE-registration
      pageRef: /Signup
      weight: 40
      
