baseURL: https://tonvanbart.github.io/europrez
title: "europrez"
defaultContentLanguage: en
languages:
    en:
        lang: en
        languageName: English
        weight: 1
MetaDataFormat: "yaml"
theme: "europrez"
menu:
    main:
    - name: Home
      pageRef: / 
    - name: News
      pageRef: /News
      title: Latest news
    - name: Past events
      pageRef: /Past
      
